### ISSUE TITLE
Precompilation error during production deployment

### ISSUE THREAD

**Issue by mrudult** [lagotto/lagotto#465]
I'm trying to deploy lagotto to a production environment. However, there seems to be error in one of the JS files which is kind of hard to trace back looking at the back trace of the `rake precompile command`.

Can anyone help me on this one? 

`$ RAILS_ENV=production rake assets:precompile --trace`

```
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke bower:before_precompile (first_time)
** Execute bower:before_precompile
** Execute assets:precompile
rake aborted!
ExecJS::ProgramError: Unexpected token: keyword (default) (line: 28623, col: 7, pos: 1032060)

Error
    at new JS_Parse_Error (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:10623)
    at js_error (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:10842)
    at croak (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:19067)
    at token_error (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:19204)
    at unexpected (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:19292)
    at semicolon (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:19765)
    at simple_statement (/private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:22538)
    at /private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:20534
    at /private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:19938
    at /private/var/folders/bq/3q3q14l50kb36dgmnp9b2xsm0000gn/T/execjs20160209-19095-diztljjs:2357:31926new JS_Parse_Error ((execjs):2357:10623)
js_error ((execjs):2357:10842)
croak ((execjs):2357:19067)
token_error ((execjs):2357:19204)
unexpected ((execjs):2357:19292)
semicolon ((execjs):2357:19765)
simple_statement ((execjs):2357:22538)
(execjs):2357:20534
(execjs):2357:19938
(execjs):2357:31926
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:39:in `exec'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/uglifier-2.5.3/lib/uglifier.rb:187:in `run_uglifyjs'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/uglifier-2.5.3/lib/uglifier.rb:170:in `compile'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:52:in `call'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:142:in `block in find'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `each'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `stat_directory'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:224:in `stat_tree'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `each'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `each'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:140:in `find'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:168:in `compile'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-3.5.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/mrudul/.rvm/gems/ruby-2.2.3/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/mrudul/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/mrudul/.rvm/gems/ruby-2.2.3/bin/rake:23:in `load'
/Users/mrudul/.rvm/gems/ruby-2.2.3/bin/rake:23:in `<main>'
/Users/mrudul/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/mrudul/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by mfenner** [comment]
What Lagotto version are you using? Head of `master` branch? And how do you provide javascript support, by installing `nodejs`?

**Comment by mrudult** [comment]
Yup. I'm using Head of master branch with nodejs installed and Ruby 2.2.3p173

**Comment by mfenner** [comment]
What happens if you go into `/frontend` and run `npm install`? The error messages, if any, might be more informative.

**Comment by mrudult** [comment]
No errors in `/frontend`. Everything installs correctly.

**Comment by mrudult** [comment]
Well, the issue was in a [third party library](https://github.com/lagotto/lagotto/blob/master/app/assets/javascripts/application.js#L15) which was actually caused by [this line](https://github.com/d3/d3-queue/blob/master/src/queue.js#L101).

I had to remove that file to make it work. But I'm still not able to understand why `application.js` has references to all the third-party js files which are not even present in the assets directory?

**Comment by mfenner** [comment]
The short answer is that I use an approach that is a bit unusual for Rails apps: using bower to install js libraries and then feed them into sprockets [here](https://github.com/lagotto/lagotto/blob/master/config/application.rb#L40). In other words, I am using a different assets directory.

**Comment by weixing2014** [comment]
@mfenner Hi, I'm wondering if you fixed this issue? I'm running into the same issue as you had. Thanks!

**Comment by mrudult** [comment]
@weixing2014 I had to manually download a d3js library to fix this.

**Comment by mfenner** [comment]
@mrudult can you explain? I can't reproduce the error, but might install lagotto differently.
