### ISSUE TITLE
Lagotto installation / migration issues

### ISSUE THREAD

**Issue by afandian** [lagotto/lagotto#509]
Running standard `cap production deploy` doesn't work on a new server. Data migrations for Events reference classes that now don't exist. 

```
rake stdout: == 20150324114452 ChangeMetricsDefaultToZero: migrating - Shard: master =======
rake stderr: rake aborted!
StandardError: An error has occurred, all later migrations canceled:

uninitialized constant ChangeMetricsDefaultToZero::Event/var/www/ced_production/releases/20160331165734/db/data_migrate/20150324114452_change_metrics_default_to_zero.rb:3:in `up'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/migration.rb:611:in `exec_migration'
```

Running `bundle exec rake db:setup` directly with an empty db on the server also fails (after working for a bit)

```
D, [2016-03-31T19:23:20.605226 #22188] DEBUG -- : Planting Source with sprig_id crossref
I, [2016-03-31T19:23:20.655306 #22188]  INFO -- : Saved
D, [2016-03-31T19:23:20.655374 #22188] DEBUG -- : Planting Source with sprig_id scopus
rake aborted!
NoMethodError: undefined method `eventable=' for #<Source:0x00000004aa6758>
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activemodel-4.2.6/lib/active_model/attribute_methods.rb:433:in `method_missing'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/seed/record.rb:35:in `block in populate_attributes'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/seed/attribute_collection.rb:6:in `each'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/seed/attribute_collection.rb:6:in `each'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/seed/record.rb:34:in `populate_attributes'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/seed/record.rb:21:in `save'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/seed/entry.rb:30:in `save_record'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/planter.rb:31:in `plant'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/planter.rb:9:in `block in sprig'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/planter.rb:8:in `each'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/planter.rb:8:in `sprig'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/sprig-0.1.9/lib/sprig/helpers.rb:10:in `sprig'
/var/www/ced_production/releases/20160331170319/db/seeds/development.rb:7:in `<top (required)>'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/var/www/ced_production/releases/20160331170319/db/seeds.rb:6:in `<top (required)>'
/var/www/ced_production/shared/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
```

**Comment by mfenner** [comment]
Fixed migrations. Tested a fresh install.
