### ISSUE TITLE
404 from doi.org not handled

### ISSUE THREAD

**Issue by pbinkley** [lagotto/lagotto#648]
We're finding notifications of non-existent DOIs due to 404s from doi.org, for DOIs that are actually ok. When this happens an empty object gets stored in the deposits table, and this ends up causing a notification like "Validation failed: Month can't be blank".

Example - notifications table, showing the 404 from doi.org:

> `id, source_id, class_name, message, trace, target_url, user_agent, status, content_type, details, unresolved, created_at, updated_at, remote_ip, work_id, level, hostname, uuid, deposit_id`
> `'11', NULL, 'Net::HTTPNotFound', 'DOI 10.1371/journal.pone.0036790 could not be resolved', '/app/models/concerns/resolvable.rb:15:in `get_canonical_url\'\n/app/models/work.rb:102:in `get_url\'\n/app/models/agents/wikipedia.rb:5:in `get_query_url\'\n/app/models/agents/wikipedia.rb:29:in `block in get_data\'\n/app/models/agents/wikipedia.rb:26:in `each\'\n/app/models/agents/wikipedia.rb:26:in `reduce\'\n/app/models/agents/wikipedia.rb:26:in `get_data\'\n/app/models/agent.rb:158:in `collect_data\'\n/app/jobs/agent_job.rb:37:in `block (3 levels) in perform\'\n/app/jobs/agent_job.rb:36:in `block (2 levels) in perform\'\n/app/jobs/agent_job.rb:20:in `each\'\n/app/jobs/agent_job.rb:20:in `block in perform\'\n/app/jobs/agent_job.rb:18:in `perform\'', 'http://doi.org/10.1371/journal.pone.0036790', NULL, '404', NULL, '<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /10.1371/journal.pone.0036790 was not found on this server.</p>\n<hr>\n<address>Apache/2.4.7 (Ubuntu) Server at doi.org Port 80</address>\n</body></html>\n', '1', '2016-09-16 22:27:29', '2016-09-16 22:27:29', NULL, '1', '3', 'lagotto-uat', '2606fdd8-be22-47e4-a72a-e0ecd7186076', NULL`

And the corresponding row of the deposits table, showing the "month can't be blank" error:

> `id, uuid, message_type, source_token, callback, state, state_event, created_at, updated_at, message_action, prefix, subj_id, obj_id, relation_type_id, source_id, publisher_id, subj, obj, total, occurred_at, error_messages, work_id, related_work_id, contributor_id`
> `'8', 'e495c45a-9366-4726-863a-bda097f44684', 'relation', '5cdf3809-7f38-440b-955f-91a86e2457eb', NULL, '2', NULL, '2016-09-22 23:26:42', '2016-09-22 23:29:47', 'create', '10.1371', 'http://doi.org/10.7717/peerj.1032', 'http://doi.org/10.1371/journal.pone.0036790', 'cites', 'pubmed', NULL, '{\"pid\":\"http://doi.org/10.7717/peerj.1032\",\"issued\":\"2015-06-18\",\"author\":[{\"family\":\"Cau\",\"given\":\"Andrea\"},{\"family\":\"Brougham\",\"given\":\"Tom\"},{\"family\":\"Naish\",\"given\":\"Darren\"}],\"container-title\":\"PeerJ\",\"volume\":\"3\",\"issue\":null,\"page\":\"e1032\",\"title\":\" The phylogenetic affinities of the bizarre Late Cretaceous Romanian theropod Balaur bondoc (Dinosauria, Maniraptora): dromaeosaurid or flightless bird? \",\"DOI\":\"10.7717/peerj.1032\",\"PMID\":\"26157616\",\"PMCID\":\"4476167\",\"type\":\"article-journal\",\"tracked\":false,\"publisher_id\":\"4443\",\"registration_agency\":\"crossref\"}', '{}', '1', '2016-09-22 23:26:42', '{\"relation\":\"Validation failed: Month can\'t be blank\"}', '4', '1', NULL`

Note that the failed DOI, http://doi.org/10.1371/journal.pone.0036790, is the object in the relationship, and the `obj` field in the deposits table ends up holding an empty JSON object: "{}".

**Comment by afandian** [comment]
Are you seeing many of these? It's a problem if the DOI resolver isn't recognising DOIs. I'll report this back within Crossref.

**Comment by ckoscher** [comment]
I've passed this on to CNRI. I know there have been some handle server changes recently, for example yesterday between 5 and 7PM EDT. Could be that this caused some temporary disturbances.
